FROM node:latest
LABEL maintainer="Lee Boonstra"

WORKDIR /my-app

COPY package.json /my-app/
COPY angular.json /my-app/
COPY tsconfig.json /my-app/
COPY tslint.json /my-app/
COPY webpack.server.config.js /my-app/
COPY server.ts /my-app/

RUN npm set progress=false && npm config set depth 0 && npm cache clean --force
RUN npm install --force

COPY /src/ /my-app/src/

RUN npm run build:ssr -- --output-path=./dist/front-end-server/
RUN npm run webpack:server -- --output-path=./dist/
RUN npm install pm2 -g

EXPOSE 4000

CMD ["pm2-runtime", "./dist/server.js"]
