#!/bin/bash

# install script
PROJECT_ID=$(gcloud info --format='value(config.project)')
PROD_AGENT_NAME=chatbotportal
PROJECT_NUMBER=$(gcloud projects describe $PROJECT_ID --format="value(projectNumber)")

VERSION=1.0.0
COMMIT_SHA=`git rev-parse HEAD`
CLOUD_BUILD_EMAIL=$PROJECT_NUMBER@cloudbuild.gserviceaccount.com

# setup service account
SERVICE_ACCOUNT_NAME="chatbotportal-app-$(date +"%s")"
SA_EMAIL=$(gcloud iam service-accounts list \
  --filter="displayName:$SERVICE_ACCOUNT_NAME" \
  --format='value(email)')
CLOUD_BUILD_EMAIL=$PROJECT_NUMBER@cloudbuild.gserviceaccount.com

# Storage Bucket
GCLOUD_STORAGE_BUCKET_NAME=$PROJECT_NUMBER-app

# setup GKE
MIN_NODES=1
MAX_NODES=4
GKE_CLUSTER=chatbotportal
REGION=europe-west4-a
REGION_ALTERNATIVE=europe-west1
# setup Cloud Functions
CF_ANALYTICS=chatanalytics

# TODO get environment vars


