# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('isWish', models.BooleanField()),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
