# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160626_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='isWish',
            new_name='on_wish_list',
        ),
    ]
